import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import { IsInt, IsOptional, IsString, IsUrl, Min } from 'class-validator';

/**
 * DTO for submitting a recorded video response to a single question.
 * videoUrl must be a pre-signed S3 URL generated by /uploads/presigned-url.
 */
export class SubmitResponseDto {
  @ApiProperty({ example: 0, description: 'Zero-based index of the question being answered' })
  @IsInt()
  @Min(0)
  questionIndex: number;

  @ApiProperty({
    example: 'https://s3.amazonaws.com/beleqet-uploads/interviews/abc.webm',
    description: 'Pre-signed S3 URL pointing to the uploaded video file',
  })
  @IsUrl()
  videoUrl: string;

  @ApiPropertyOptional({
    example: 'en',
    default: 'en',
    description: 'BCP-47 language tag for Whisper',
  })
  @IsOptional()
  @IsString()
  language?: string;
}
